### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by Rysakov1986** [nicksulkers/another-svelte-router#3]
Hello! How to forwarding meta to page?

maybe:
```javascript
return { data: 123 };
``

**Comment by nicksulkers** [comment]
I'm not entirely sure what you're looking for.
Could you describe your use-case?

Currently there are no built-in features to pass data to a page (except through the url). But I could imagine a feature that would allow something like:

     router.navigate('/users/:username', {
          'params': {
               'username': 'peterpanda'
          }
     })

Which would ofc. just be a helper to build urls in a way that feels similiar to how the routes are defined. After which they're accessible through router.params.

and/or

     router.navigate('/registration', {
          'meta': {
               'previous-page-context-data': 123
          }
     })

In which meta would be internally passed to the next page where it'd be accessible through for example `router.meta`.

Would those be helpful?

**Comment by Rysakov1986** [comment]
Yes, second example with the meta, In which is internally passed to the next page.

Thanks!

**Comment by nicksulkers** [comment]
@Rysakov1986 Thank you for the feedback. I've implemented both in version 1.2.0 as shown in the code examples above.

The meta is also stored in the history state, so will be kept when going 'back' to a page.
