### ISSUE TITLE
on/off

### ISSUE THREAD

**Issue by Rysakov1986** [nicksulkers/another-svelte-router#4]
What are these functions on/off, where can they be used?

**Comment by nicksulkers** [comment]
They are a (still undocumented) feature to add or remove events to the router.
The current built-in events are 'beforeRouteChange' and 'afterRouteChange', which are used internally by the RouterView to re-render the correct Page component.
They're used like this:

    router.on('beforeRouteChange', () => {
        console.log('A new page will soon open');
    }

    router.on('afterRouteChange', () => {
        console.log('A new page has opened');
    }

Use these at your own risk. They should for the time being be treated as 'unofficial' features that may change in future versions.
